### PR TITLE
Redirect fixes

### LINKED ISSUE #2264: Redirects
## Context

We have a fundamental problem with redirects that already occurred a couple of times and we only noticed by accident. There might be a higher number of failed redirects.

## The Problem

When a user deletes or renames a file, the user must add an entry to the redirects.yml file. The key is the path to the deleted/renamed file and the value is the path to the new file.

The redirect is built using this path. **However**, the path might be different in production because it is wired differently through navigation.yml.

## Request

We need a safe and reliable way to set up redirects.

### PR DESCRIPTION
**Pull request by cotti**
Closes #2264 

This PR fixes the following scenario involving redirect sanitization:

### Empty redirect targets

An incorrect input for the redirect target (such as a cross-link not registered in the link index) output an error, but didn't properly register one at the collector. This caused docs-builder to proceed, yielding an empty string as a resolved path.

At a later point in the assemble process, during key-value store updates, the redirect was being set as an empty string.

### CODE REVIEW

File: src/services/Elastic.Documentation.Assembler/Building/AssemblerBuilder.cs [hunk 1]
```diff
@@ -116,7 +116,7 @@ string Resolve(string path)
 			if (Uri.IsWellFormedUriString(path, UriKind.Absolute)) // Cross-repo links
 			{
 				_ = linkResolver.TryResolve(
-					e => _logger.LogError("An error occurred while resolving cross-link {Path}: {Error}", path, e),
+					e => context.Collector.EmitError(path, $"An error occurred while resolving cross-link {path}: {e}", null),
```
Comment (reakaleek) [inline src/services/Elastic.Documentation.Assembler/Building/AssemblerBuilder.cs]: I 
```suggestion
					e => context.Collector.EmitError(path, $"An error occurred while resolving cross-link {path}", e),
```

Comment (cotti) [reply src/services/Elastic.Documentation.Assembler/Building/AssemblerBuilder.cs]: So a new overload for EmitError to support this? (e is a string in this context)

**Review by reakaleek — APPROVED** [review]
